/**
 * The shared traffic source: one per Scenario. It generates new Requests as simulated time
 * advances and appends them to one log, which every Variant's engine reads through its own
 * reader, so every Variant sees identical arrivals and the comparison stays fair.
 *
 * Arrivals are generated exactly up to the time asked for, never ahead, and the next arrival
 * is computed once and kept between calls. How a run is sliced into frames therefore never
 * changes the log (.scratch/traffic/spec.md, decisions 4 and 5).
 *
 * The log only grows: about 3.6 million entries per simulated hour at 1,000 rps. Trimming
 * entries every reader has passed is left to the runner (RS-15).
 */
import type { RandomStream } from './rng.ts'
import {
  checkTrafficSpec,
  clientWeights,
  gapWork,
  pickClient,
  rateProfile,
  timeToWork,
  type ClientId,
  type RateProfile,
  type TrafficShape,
  type TrafficSpec,
  workBetween,
} from './traffic.ts'

/** A Request's id: its position in the shared log, so every Variant uses the same id. */
export type RequestId = number

/** One new Request in the shared log. */
export interface Arrival {
  readonly requestId: RequestId
  /** When the Request arrives, in ms of simulated time. */
  readonly atMs: number
  readonly clientId: ClientId
  /** Generated by the arrival process, or listed in the Scenario (such as an Edge Burst). */
  readonly origin: 'generated' | 'scripted'
}

/** A cursor over the shared log for one Variant. Readers move independently. */
export interface TrafficReader {
  /**
   * The arrivals this reader has not yet returned, up to and including `untilMs`. Throws a
   * RangeError if `untilMs` is past the source's horizon: the source must be advanced first.
   */
  read(untilMs: number): Arrival[]
}

/** The shared traffic of one Scenario. */
export interface TrafficSource {
  /** How far the source has generated, in ms: every arrival at or before this is in the log. */
  horizonMs(): number
  /**
   * Generates every arrival up to and including `untilMs`, and nothing later. Moving to the
   * current horizon does nothing; moving backwards throws a RangeError.
   */
  advanceTo(untilMs: number): void
  /** A new reader starting at the beginning of the log. */
  reader(): TrafficReader
  /**
   * Applies a load change at the current horizon and records it. It affects arrivals after
   * the horizon; arrivals at exactly the horizon are already in the log. Throws a RangeError
   * on an invalid change, leaving the source unchanged.
   */
  applyControl(change: ControlChange): void
  /** Every change applied so far, scripted and live, in the order applied. */
  timeline(): readonly ControlEvent[]
}

/** One load change: the Demand slider, the greedy multiplier, the burst button or the shape. */
export type ControlChange =
  | { readonly kind: 'demand'; readonly rps: number }
  /**
   * Sets one Client's share weight to `x`. Other Clients keep theirs, so moving the multiplier
   * to a new Client leaves the previous greedy Client's weight as it was.
   */
  | { readonly kind: 'greedyMultiplier'; readonly clientId: ClientId; readonly x: number }
  | { readonly kind: 'burst'; readonly multiplier: number; readonly durationMs: number }
  | { readonly kind: 'shape'; readonly shape: TrafficShape }

/**
 * A load change and when it happened, in ms of simulated time. Seed plus the list of these
 * replays a run exactly.
 */
export interface ControlEvent {
  readonly simTime: number
  readonly change: ControlChange
}

/** Requests listed in the Scenario at an exact time, such as an Edge Burst (D12). */
export interface ScriptedArrivals {
  /** When they arrive, in ms of simulated time. */
  readonly atMs: number
  /** How many Requests arrive at that time. */
  readonly count: number
  /** Who sends them; the first listed Client when left out. */
  readonly clientId?: ClientId
}

/** What a traffic source is built from. */
export interface TrafficSourceOptions {
  readonly spec: TrafficSpec
  /** The `traffic` stream. It is the only randomness the source uses. */
  readonly stream: RandomStream
  /** Merged into the log at their times. They never draw from the stream. */
  readonly scriptedArrivals?: readonly ScriptedArrivals[]
  /**
   * Changes applied when generation reaches their time, after arrivals at that same time:
   * Scenario presets, or a recorded `timeline()` to replay. Must be in time order.
   */
  readonly controls?: readonly ControlEvent[]
}

const SHAPES: readonly TrafficShape[] = ['constant', 'poisson', 'bursty']

/** Throws a RangeError unless `change` is valid for `spec`. */
function checkChange(spec: TrafficSpec, change: ControlChange): void {
  const bad = (what: string, value: unknown) => new RangeError(`${what}, got ${String(value)}`)
  const finite = (value: number) => Number.isFinite(value)
  switch (change.kind) {
    case 'demand':
      if (!finite(change.rps) || change.rps < 0)
        throw bad('Demand must be a finite number of rps, 0 or more', change.rps)
      return
    case 'greedyMultiplier':
      if (!spec.clients.includes(change.clientId))
        throw bad('The greedy Client must be one of the Clients', change.clientId)
      if (!finite(change.x) || change.x <= 0)
        throw bad('The greedy multiplier must be finite and more than 0', change.x)
      return
    case 'burst':
      if (!finite(change.multiplier) || change.multiplier <= 0)
        throw bad('The burst multiplier must be finite and more than 0', change.multiplier)
      if (!finite(change.durationMs) || change.durationMs <= 0)
        throw bad('The burst must last a finite number of ms, more than 0', change.durationMs)
      return
    case 'shape':
      if (!SHAPES.includes(change.shape)) throw bad('Unknown traffic shape', change.shape)
      if (change.shape === 'bursty' && spec.bursty === undefined)
        throw bad('Bursty traffic needs on and off phases in the spec', change.shape)
      return
    default:
      throw bad('Unknown control change', (change as { kind: unknown }).kind)
  }
}

/**
 * The next generated arrival. `work` is the gap's work still to be done from `fromMs`; a
 * control change moves `fromMs` to the change time and keeps what is left of `work`.
 */
interface Pending {
  readonly fromMs: number
  readonly work: number
  readonly atMs: number
}

/**
 * Checks the scripted arrivals and expands them into one entry per Request, in time order.
 * Equal times keep their listed order (Array.prototype.sort is stable). A missing clientId
 * becomes the first listed Client rather than a draw, so scripted arrivals never shift the
 * generated ones.
 */
function expandScripted(
  scripted: readonly ScriptedArrivals[],
  clients: readonly ClientId[],
): { atMs: number; clientId: ClientId }[] {
  const expanded: { atMs: number; clientId: ClientId }[] = []
  for (const { atMs, count, clientId = clients[0] as ClientId } of scripted) {
    if (!Number.isFinite(atMs) || atMs < 0) {
      throw new RangeError(
        `A scripted arrival time must be a finite number of ms, 0 or more, got ${atMs}`,
      )
    }
    if (!Number.isInteger(count) || count < 1) {
      throw new RangeError(
        `A scripted arrival count must be a whole number, 1 or more, got ${count}`,
      )
    }
    if (!clients.includes(clientId)) {
      throw new RangeError(`The scripted arrival Client ${clientId} is not one of the Clients`)
    }
    for (let i = 0; i < count; i++) expanded.push({ atMs, clientId })
  }
  return expanded.sort((a, b) => a.atMs - b.atMs)
}

/**
 * Creates a source and generates up to time 0, so arrivals at 0 are in the log from the
 * start. Throws a RangeError if the spec or a scripted arrival is invalid.
 *
 * Draw order: the first gap's work is drawn here. Each generated arrival then draws its
 * Client pick when it is emitted, followed by the work of the gap after it.
 */
export function createTrafficSource(options: TrafficSourceOptions): TrafficSource {
  const { spec, stream } = options
  checkTrafficSpec(spec)
  let profile: RateProfile = rateProfile(spec)
  const weights = clientWeights(spec)
  let shape = spec.shape
  const scripted = expandScripted(options.scriptedArrivals ?? [], spec.clients)
  const controls = options.controls ?? []
  controls.forEach(({ simTime, change }, i) => {
    if (!Number.isFinite(simTime) || simTime < 0) {
      throw new RangeError(
        `A control time must be a finite number of ms, 0 or more, got ${simTime}`,
      )
    }
    if (simTime < (controls[i - 1]?.simTime ?? 0)) {
      throw new RangeError(
        `Controls must be in time order, got ${simTime} ms after ${controls[i - 1]?.simTime} ms`,
      )
    }
    checkChange(spec, change)
  })
  let nextControl = 0
  let nextScripted = 0
  const log: Arrival[] = []
  const applied: ControlEvent[] = []
  let horizon = 0

  /** Times a gap of `work` from `fromMs` at the current rate. */
  function timed(fromMs: number, work: number): Pending {
    return { fromMs, work, atMs: timeToWork(profile, fromMs, work) }
  }

  /** Draws the work of the gap after an arrival at `fromMs` and times it. */
  function schedule(fromMs: number): Pending {
    return timed(fromMs, gapWork(shape, stream))
  }

  /**
   * Applies a change at `atMs` and records it. When the rate over time changes, the pending
   * arrival keeps the work its gap has left and is re-timed at the new rate, with no new draw:
   * a Poisson gap is memoryless, and a constant gap keeps its remaining fraction. Changes that
   * leave the rate alone (the greedy multiplier, the same shape again) leave the pending
   * arrival exactly as it was.
   */
  function apply(atMs: number, change: ControlChange): void {
    checkChange(spec, change)
    const before = profile
    switch (change.kind) {
      case 'demand':
        profile = { ...profile, demandRps: change.rps }
        break
      case 'burst':
        // A new burst replaces an active one, multiplier and end time both.
        profile = {
          ...profile,
          burst: { multiplier: change.multiplier, endMs: atMs + change.durationMs },
        }
        break
      case 'greedyMultiplier':
        // Only who sends changes: the next pick uses the new weights.
        weights[spec.clients.indexOf(change.clientId)] = change.x
        break
      case 'shape':
        if (change.shape !== shape) {
          shape = change.shape
          // Phases start at the switch, so a student who flips to bursty sees an on phase at once.
          const phases = shape === 'bursty' ? (spec.bursty ?? null) : null
          profile = { ...profile, phases, phaseAnchorMs: atMs }
        }
        break
    }
    if (profile !== before) {
      const left = Math.max(0, pending.work - workBetween(before, pending.fromMs, atMs))
      pending = timed(atMs, left)
    }
    applied.push({ simTime: atMs, change })
  }

  let pending = schedule(0)

  /**
   * Appends every arrival up to and including `untilMs` in time order, applying scripted
   * controls on the way. At equal times the order is scripted arrivals, then the generated
   * arrival, then the control, which matches a live change made at the horizon after the
   * arrivals at the horizon are already in the log.
   */
  function generateUntil(untilMs: number): void {
    for (;;) {
      const scriptedAtMs = scripted[nextScripted]?.atMs ?? Number.POSITIVE_INFINITY
      const control = controls[nextControl]
      const controlAtMs = control?.simTime ?? Number.POSITIVE_INFINITY
      if (scriptedAtMs <= untilMs && scriptedAtMs <= pending.atMs && scriptedAtMs <= controlAtMs) {
        const { atMs, clientId } = scripted[nextScripted++] as { atMs: number; clientId: ClientId }
        log.push({ requestId: log.length, atMs, clientId, origin: 'scripted' })
      } else if (pending.atMs <= untilMs && pending.atMs <= controlAtMs) {
        const atMs = pending.atMs
        const clientId = pickClient(spec.clients, weights, stream)
        log.push({ requestId: log.length, atMs, clientId, origin: 'generated' })
        pending = schedule(atMs)
      } else if (control !== undefined && controlAtMs <= untilMs) {
        nextControl++
        apply(controlAtMs, control.change)
      } else {
        return
      }
    }
  }

  generateUntil(0)

  return {
    horizonMs() {
      return horizon
    },
    advanceTo(untilMs) {
      if (!Number.isFinite(untilMs) || untilMs < horizon) {
        throw new RangeError(`Traffic can only advance forward from ${horizon} ms, got ${untilMs}`)
      }
      generateUntil(untilMs)
      horizon = untilMs
    },
    applyControl(change) {
      apply(horizon, change)
    },
    timeline() {
      return [...applied]
    },
    reader() {
      let next = 0
      return {
        read(untilMs) {
          if (untilMs > horizon) {
            throw new RangeError(`Traffic is generated up to ${horizon} ms, asked for ${untilMs}`)
          }
          const start = next
          while (next < log.length && (log[next]?.atMs ?? Infinity) <= untilMs) next++
          return log.slice(start, next)
        },
      }
    },
  }
}
